# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Portfolio Variables'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - script: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set "//npm.fontawesome.com/:_authToken" $(fontAwesomeToken)
      displayName: 'Apply npm private packages keys'
    - script: |
        npm install
        npm run build --if-present
      displayName: 'npm install and build'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/dist'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop
- stage: Deploy
  displayName: Deploy Stage
  jobs: 
  - deployment: VMDeploy
    displayName: Deploy into VM
    environment:
      name: 'portfolio-env'
      resourceType: VirtualMachine
    strategy:
        rolling:
          maxParallel: 5  #for percentages, mention as x%
          preDeploy:
            steps:
            - download: current
              artifact: drop
            - script: echo initialize, cleanup, backup, install certs
          deploy:
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  rm -rf $(sshStaticPath) || true
                  mkdir $(sshStaticPath) || true
                  cp -r $(Pipeline.Workspace)/drop/* $(sshStaticPath)
                  rm -rf $(Pipeline.Workspace) || true
          on:
            failure:
              steps:
              - script: echo Restore from backup! This is on failure
            success:
              steps:
              - script: echo Notify! This is on success
