# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Portfolio Variables'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    environment:
      name: 'portfolio-env'
      resourceType: VirtualMachine
    steps:
    - script: |
        npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        npm config set "//npm.fontawesome.com/:_authToken" $(fontAwesomeToken)
      displayName: 'Apply npm private packages keys'
    - script: |
        npm install
        echo -e "FULL_JS_LICENSE_KEY=$(FULL_JS_LICENSE_KEY)\nEMAIL_JS_SERVICE_ID=$(EMAIL_JS_SERVICE_ID)\nEMAIL_JS_TEMPLATE_ID=$(EMAIL_JS_TEMPLATE_ID)\nEMAIL_JS_USER_ID=$(EMAIL_JS_USER_ID)" > .env
        npm run build --if-present
        npm run ssr --if-present
      displayName: 'npm install and build'