# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: 'Portfolio Variables'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - deployment: VMDeploy
    displayName: Deploy into VM
    environment:
      name: 'portfolio-env'
      resourceType: VirtualMachine
    strategy:
      rolling:
        maxParallel: 5  #for percentages, mention as x%
        preDeploy:
          steps:
            - script: git clone https://github.com/daycolor/portfolio .
        deploy:
          steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  npm config set "@fortawesome:registry" https://npm.fontawesome.com/
                  npm config set "//npm.fontawesome.com/:_authToken" $(fontAwesomeToken)
                  npm install
                  echo -e "FULL_JS_LICENSE_KEY=$(FULL_JS_LICENSE_KEY)\nEMAIL_JS_SERVICE_ID=$(EMAIL_JS_SERVICE_ID)\nEMAIL_JS_TEMPLATE_ID=$(EMAIL_JS_TEMPLATE_ID)\nEMAIL_JS_USER_ID=$(EMAIL_JS_USER_ID)" > .env
                  npm run build --if-present
                  pm2 start server.js
        on:
          failure:
            steps:
              - script: echo Restore from backup! Deploy failed!
          success:
            steps:
              - script: echo Deploy succeed!