version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-job:
    executor:
      name: node/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1c:a8:2d:61:e1:3d:e1:33:a6:56:88:72:ef:ce:6c:ae"
      - run: ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
      - run:
          name: Apply npm private packages keys
          command: |
            npm config set "@fortawesome:registry" https://npm.fontawesome.com/
            npm config set "//npm.fontawesome.com/:_authToken" $FONTAWESOME_TOKEN
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - run:
          name: Clone into VM
          command: |
            sudo scp -r ./dist/* $SSH_USER@$SSH_IP:$SSH_STATIC_PATH
workflows:
    deploy:
      jobs:
        - deploy-job
