name: Portfolio Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: |
          docker build \
          -t alon/portfolio \
          --build-arg FONTAWESOME_TOKEN=$FONTAWESOME_TOKEN \
          --rm \
          .
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
  run:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: Stop docker container
        run: |
          docker container stop portfolio || true
      - name: Run docker
        run: |
          docker run \
          --name portfolio \
          --env FULLPAGE_JS_LICENSE_KEY \
          --env EMAIL_JS_SERVICE_ID \
          --env EMAIL_JS_TEMPLATE_ID \
          --env EMAIL_JS_USER_ID \
          --rm \
          -p $PORT:8080 \
          -d alon/portfolio
        env:
          PORT: ${{ secrets.PORT }}
          FULLPAGE_JS_LICENSE_KEY: ${{ secrets.FULLPAGE_JS_LICENSE_KEY }}
          EMAIL_JS_SERVICE_ID: ${{ secrets.EMAIL_JS_SERVICE_ID }}
          EMAIL_JS_TEMPLATE_ID: ${{ secrets.EMAIL_JS_TEMPLATE_ID }}
          EMAIL_JS_USER_ID: ${{ secrets.EMAIL_JS_USER_ID }}