name: Portfolio Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Dump license context
      env:
        FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}
      run: echo "$FONTAWESOME_TOKEN"
    - name: Build the Docker image
      run: sudo docker build -t alon/portfolio --build-arg FONTAWESOME_TOKEN="$FONTAWESOME_TOKEN" .
