name: Portfolio Docker Image

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: sudo docker build -t alon/portfolio --build-arg FONTAWESOME_TOKEN_ARG=$FONTAWESOME_TOKEN .
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}