name: Portfolio Docker Image

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build docker
        run: docker-compose build -e FONTAWESOME_TOKEN=$FONTAWESOME_TOKEN
        env:
          FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}